# Generated by Django 5.1.5 on 2025-01-22 02:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ecom", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="update",
            new_name="updated",
        ),
    ]
